version: '3'

services:
  app:
    container_name: pcidss-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - flask
    networks:
      - pcidss-network
    
  flask:
    container_name: pcidss-flask
    build:
      context: ./src/server
      dockerfile: Dockerfile
    volumes:
      - ./src/server:/app
      - /app/__pycache__
    networks:
      - pcidss-network

networks:
  pcidss-network:
    driver: bridge